site_name: Algothon 2023
# todo: this link is dead
repo_url: https://github.com/UNSW-Fintech-Society-Events/algothon2023-wiki
repo_name: Algothon 2023 Starter Code

theme:
  features:
    - navigation.top
    - toc.integrate
    - navigation.tabs
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: img/fintech.png
  favicon: img/fintech.png
  palette:
    primary: black
